insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Agustinas	            ','agustinas@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Ahumada	            ','ahumada@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Alto Las Condes	    ','alcondes@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Arauco Maipú	        ','amaipu@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Antofagasta	        ','antofagasta@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Anibal Pinto	        ','apinto@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Apoquindo	            ','apoquindo@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Apumanque	            ','apumanque@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('El Belloto	        ','belloto@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Lider Buenaventura    ','Buenaventura@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Costanera Center	    ','ccenter@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Cuidad Empresarial	','cempresarial@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Con Con	            ','concon@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Los Dominicos	        ','dominicos@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Plaza Egaña	        ','egana@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Isidora Goyenechea	','igoyenechea@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('La Serena 2	        ','laserena2@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('La Serena	            ','laserena@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('La Dehesa	            ','ldehesa@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Luis Pasteur	        ','lpasteur@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Portal La Reina	    ','lreina@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Lyon	                ','lyon@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Maintencillo	        ','maitencillo@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Mall del Centro	    ','mallconcepcion@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Tienda Mall Los Dominicos	','malldominicos@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Marina Arauco	        ','marina@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Nueva Las Condes	    ','nlcondes@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Open Plaza	                ','openplaza@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Parque Arauco	        ','parauco@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Portal La Dehesa	    ','pdehesa@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Pueblo del Inglés	    ','pingles@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Plaza Oeste	        ','plazaoeste@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Plaza Norte	        ','pnorte@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Portal Ñuñoa	        ','pnunoa@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Rancagua	            ','prancagua@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Piedra Roja	        ','proja@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Providencia	        ','providencia@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Puerto Montt	        ','puertomontt@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Puerto Varas	        ','puertovaras@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Pedro de Valdivia	    ','pvaldivia@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Módulo Plaza Vespucio 2	    ','pvespucio2@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Plaza Vespucio	    ','pvespucio@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Santa Amalia	        ','stamalia@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Temuco	            ','temuco@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Tenderini	            ','tenderini@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Titanium	            ','titanium@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('Plaza Tobalaba	    ','tobalaba@varsovienne.cl','',getdate(), getdate(),'',0)
insert into ktb_usuarios_vista_web (nombre,email,code,creacion,ultimo_acceso,codigo_softland,supervisor) values ('El Trebol	            ','trebol@varsovienne.cl','',getdate(), getdate(),'',0)
